spring.cloud.gateway.routes[0].id=erp-service
spring.cloud.gateway.routes[0].uri=${ERP_URI:http://prod-erp-service:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/erp/**
spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[1].id=crm-service
spring.cloud.gateway.routes[1].uri=${CRM_URI:http://prod-crm-service:8082}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/crm/**
spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[2].id=supply-chain-service
spring.cloud.gateway.routes[2].uri=${SUPPLY_URI:http://prod-supply-service:8083}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/supply/**
spring.cloud.gateway.routes[2].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[3].id=bi-service
spring.cloud.gateway.routes[3].uri=${BI_URI:http://prod-bi-service:8084}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/bi/**
spring.cloud.gateway.routes[3].filters[0]=AuthenticationFilter

jwt.secret=${JWT_SECRET_KEY}
logging.level.root=WARN
