spring.cloud.gateway.routes[0].id=erp-service
spring.cloud.gateway.routes[0].uri=${ERP_URI:http://localhost:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/erp/**
spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[1].id=crm-service
spring.cloud.gateway.routes[1].uri=${CRM_URI:http://localhost:8082}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/crm/**
spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[2].id=supply-chain-service
spring.cloud.gateway.routes[2].uri=${SUPPLY_URI:http://localhost:8083}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/supply/**
spring.cloud.gateway.routes[2].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[3].id=bi-service
spring.cloud.gateway.routes[3].uri=${BI_URI:http://localhost:8084}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/bi/**
spring.cloud.gateway.routes[3].filters[0]=AuthenticationFilter

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
logging.level.root=INFO
