erp.service.url=${ERP_SERVICE_URL:http://localhost:8081}
crm.service.url=${CRM_SERVICE_URL:http://localhost:8082}
supply.service.url=${SUPPLY_SERVICE_URL:http://localhost:8083}
logging.level.root=INFO
