erp.service.url=${ERP_SERVICE_URL:http://test-erp-service:8081}
crm.service.url=${CRM_SERVICE_URL:http://test-crm-service:8082}
supply.service.url=${SUPPLY_SERVICE_URL:http://test-supply-service:8083}
logging.level.root=INFO
