# Environnement TEST (UAT)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://test-db.internal:5432/erp_db_test}
spring.datasource.username=postgres_test
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.root=INFO
