spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://test-db.internal:5432/crm_db_test}
spring.datasource.username=postgres_test
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
logging.level.root=INFO
